Added a parameter to exlude specific file(s)
bvaughn/palettable pull request #1
Opened 2017-05-02 14:51 UTC by FBiocchetti

2017-05-02 18:14 UTC, bvaughn requested changes
In general, this seems like a reasonable change. Happy to approve it and make a new release- but I'd like to see the tests updated to cover this new functionality. (Basically add a file, then exclude it, then verify in the expected outcome that it's been properly excluded.)

2017-05-02 18:14 UTC, bvaughn commented on README.md
> +Default `/`
This default seems a bit ambiguous to me. Could be interpreted as "exclude everything under the root". Maybe we could just say "Default null" in the docs (regardless of what the actual underlying default is).

2017-05-04 15:15 UTC, merged

2017-05-04 15:16 UTC, bvaughn commented
Published 1.1.0

Thanks for the contribution

2017-05-04 15:45 UTC, FBiocchetti commented
Thanks to you for your collaboration!